### ISSUE TITLE
Success modal is missing an image

### ISSUE THREAD

**Issue by kboucher** [wllm-chndlr/Hangman-Game#2]
![image](https://user-images.githubusercontent.com/1943568/138949487-7aa99816-2392-4723-8a5a-9d8feb0e9e2a.png)

**Comment by wllm-chndlr** [comment]
Thanks for the heads up! Added new GIF with 07cf7f44b8e3f2b1ed1ea49ee5201c21bd0f9913.

<img width="538" alt="Screen Shot 2021-11-03 at 7 51 42 PM" src="https://user-images.githubusercontent.com/26122916/140250084-34ecfb9c-a706-4c4c-bc87-388db8847b35.png">
